name: llm_engineering
channels:
  - conda-forge
  - defaults
dependencies:
  - accelerate=0.33.0
  - aiofiles=22.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - ansi2html=1.9.1
  - anthropic=0.34.1
  - anyio=4.2.0
  - aom=3.9.1
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.7.26
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.27
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.8
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.28.1
  - aws-sdk-cpp=1.11.379
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.11.0
  - backoff=2.2.1
  - bcrypt=4.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli=1.0.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - chroma-hnswlib=0.7.3
  - chromadb=0.4.14
  - click=8.1.7
  - coloredlogs=15.0.1
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=43.0.0
  - cycler=0.11.0
  - dash=2.14.2
  - datasets=2.19.1
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distro=1.9.0
  - executing=0.8.3
  - expat=2.6.2
  - faiss=1.8.0
  - faiss-cpu=1.8.0
  - fastapi=0.112.2
  - ffmpeg=7.0.2
  - ffmpy=0.3.0
  - filelock=3.13.1
  - flask=3.0.3
  - flask-compress=1.13
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.8.7
  - google-ai-generativelanguage=0.6.6
  - google-api-core=2.19.1
  - google-api-python-client=2.143.0
  - google-auth=2.29.0
  - google-auth-httplib2=0.2.0
  - google-generativeai=0.7.2
  - googleapis-common-protos=1.63.2
  - gradio=4.42.0
  - gradio-client=1.3.0
  - graphite2=1.3.14
  - greenlet=3.0.1
  - grpcio=1.62.2
  - h11=0.14.0
  - harfbuzz=9.0.0
  - httpcore=1.0.2
  - httplib2=0.22.0
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - humanfriendly=10.0
  - icu=75.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - ipywidgets=8.1.2
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jiter=0.5.0
  - joblib=1.4.2
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-dash=0.4.2
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - langchain=0.2.15
  - langchain-chroma=0.1.3
  - langchain-core=0.2.37
  - langchain-openai=0.1.23
  - langchain-text-splitters=0.2.2
  - langsmith=0.1.108
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.22.5
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.9.1
  - libcxx=18.1.8
  - libdeflate=1.21
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libfaiss=1.8.0
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.80.3
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libintl=0.22.5
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.21
  - libopenvino=2024.3.0
  - libopenvino-arm-cpu-plugin=2024.3.0
  - libopenvino-auto-batch-plugin=2024.3.0
  - libopenvino-auto-plugin=2024.3.0
  - libopenvino-hetero-plugin=2024.3.0
  - libopenvino-ir-frontend=2024.3.0
  - libopenvino-onnx-frontend=2024.3.0
  - libopenvino-paddle-frontend=2024.3.0
  - libopenvino-pytorch-frontend=2024.3.0
  - libopenvino-tensorflow-frontend=2024.3.0
  - libopenvino-tensorflow-lite-frontend=2024.3.0
  - libopus=1.3.1
  - libparquet=17.0.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libpulsar=3.5.1
  - libre2-11=2023.09.01
  - libsentencepiece=0.2.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libtorch=2.4.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=2.0.4
  - monotonic=1.5
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.3
  - nomkl=3.0
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - onnxruntime=1.17.1
  - openai=1.37.0
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.2
  - orjson=3.9.15
  - overrides=7.4.0
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.44
  - pexpect=4.8.0
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.22.0
  - posthog=3.5.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - proto-plus=1.24.0
  - protobuf=4.25.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulsar-client=3.5.0
  - pure_eval=0.2.2
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycparser=2.21
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydub=0.25.1
  - pygments=2.15.1
  - pyopenssl=24.2.1
  - pyparsing=3.0.9
  - pypika=0.48.9
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-multipart=0.0.9
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytorch=2.4.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.7.24
  - requests=2.32.3
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.10.6
  - rsa=4.7.2
  - ruff=0.3.5
  - safetensors=0.4.4
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - semantic_version=2.8.5
  - send2trash=1.8.2
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=72.2.0
  - shellingham=1.5.0
  - six=1.16.0
  - sleef=3.6.1
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.30
  - stack_data=0.2.0
  - starlette=0.38.2
  - svt-av1=2.2.1
  - sympy=1.13.2
  - tbb=2021.12.0
  - tenacity=8.2.3
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tiktoken=0.7.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.19.1
  - tomlkit=0.12.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - transformers=4.41.2
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uritemplate=4.1.1
  - urllib3=2.2.2
  - uvicorn=0.20.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=10.4
  - werkzeug=3.0.3
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.3.1
  - zstd=1.5.6
